import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiPython,
  SiPostgresql,
  SiRedis,
  SiDocker,
  SiNginx,
  SiGit,
  SiTypescript,
  SiNodedotjs,
  SiReact,
  SiSass,
  SiJson,
  SiHtml5,
  SiCss3,
  SiMysql,
  SiSwagger,
  SiExpress,
  SiFastapi,
  SiBootstrap,
  SiMongodb,
  SiTailwindcss,
  SiGraphql,
  SiJest,
  SiGo,
  SiKubernetes,
  SiTerraform,
  SiVercel,
  SiAuth0,
  SiKeycloak,
  SiOkta,
  SiClerk,
} from "react-icons/si";

import { FaJava } from "react-icons/fa";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaAws, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  python: SiPython,
  java: FaJava,
  postgresql: SiPostgresql,
  redis: SiRedis,
  docker: SiDocker,
  nginx: SiNginx,
  git: SiGit,
  typescript: SiTypescript,
  nodejs: SiNodedotjs,
  react: SiReact,
  api: SiSwagger,
  restapi: SiSwagger,
  swagger: SiSwagger,
  middleware: SiExpress,
  express: SiExpress,
  fastapi: SiFastapi,
  scss: SiSass,
  sass: SiSass,
  json: SiJson,
  html: SiHtml5,
  html5: SiHtml5,
  css: SiCss3,
  css3: SiCss3,
  sql: SiMysql,
  mysql: SiMysql,
  bootstrap: SiBootstrap,
  aws: FaAws,
  mongodb: SiMongodb,
  tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  graphql: SiGraphql,
  jest: SiJest,
  go: SiGo,
  golang: SiGo,
  kubernetes: SiKubernetes,
  terraform: SiTerraform,
  vercel: SiVercel,
  auth0: SiAuth0,
  keycloak: SiKeycloak,
  okta: SiOkta,
  clerk: SiClerk,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
