'use client';

import { useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { motion } from 'framer-motion';
import styles from './KanbanCard.module.scss';
import classNames from 'classnames';
import { User, Clock, Zap } from 'lucide-react';

export interface DealCardData {
  id: string;
  client: string;
  eventType: string;
  value: number;
  probability: number;
  daysInStage: number;
  contactName: string;
  services: string[];
  autoGenerated?: boolean;
}

interface KanbanCardProps {
  deal: DealCardData;
  isDragging?: boolean;
}

export function KanbanCard({ deal, isDragging = false }: KanbanCardProps) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging: isSortableDragging,
  } = useSortable({ id: deal.id });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
  };

  const getProgressColor = (prob: number) => {
    if (prob >= 80) return '#22c55e';
    if (prob >= 50) return '#eab308';
    return '#f97316';
  };

  return (
    <motion.div
      ref={setNodeRef}
      style={style}
      className={classNames(
        styles.card,
        (isDragging || isSortableDragging) && styles.dragging
      )}
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.95 }}
      {...attributes}
      {...listeners}
    >
      {deal.autoGenerated && (
        <div className={styles.autoTag}>
          <Zap size={10} />
          <span>Auto-generated</span>
        </div>
      )}
      
      <div className={styles.cardHeader}>
        <span className={styles.clientName}>{deal.client}</span>
        <span className={styles.dealValue}>${(deal.value / 1000).toFixed(0)}K</span>
      </div>

      <div className={styles.eventType}>{deal.eventType}</div>

      <div className={styles.services}>
        {deal.services.slice(0, 2).map((service) => (
          <span key={service} className={styles.serviceTag}>
            {service}
          </span>
        ))}
        {deal.services.length > 2 && (
          <span className={styles.serviceMore}>+{deal.services.length - 2}</span>
        )}
      </div>

      <div className={styles.cardFooter}>
        <div className={styles.contact}>
          <User size={12} />
          <span>{deal.contactName}</span>
        </div>
        <div className={styles.days}>
          <Clock size={12} />
          <span>{deal.daysInStage}d</span>
        </div>
      </div>

      <div className={styles.progressBar}>
        <div 
          className={styles.progressFill} 
          style={{ 
            width: `${deal.probability}%`,
            backgroundColor: getProgressColor(deal.probability)
          }} 
        />
      </div>
      <div className={styles.probability}>{deal.probability}% probability</div>
    </motion.div>
  );
}
