'use client';

import { useState } from 'react';
import {
  DndContext,
  DragOverlay,
  closestCorners,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
  DragStartEvent,
  DragEndEvent,
} from '@dnd-kit/core';
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
  verticalListSortingStrategy,
} from '@dnd-kit/sortable';
import { motion, AnimatePresence } from 'framer-motion';
import { DemoLayout } from '../ui/DemoLayout';
import { KanbanColumn } from './KanbanColumn';
import { KanbanCard, DealCardData } from './KanbanCard';
import styles from './SalesPipelineDemo.module.scss';
import { 
  DollarSign, 
  TrendingUp, 
  Clock, 
  Users,
  Zap,
  CheckCircle2
} from 'lucide-react';

interface ColumnData {
  id: string;
  title: string;
  color: string;
  deals: DealCardData[];
}

const initialColumns: ColumnData[] = [
  {
    id: 'quote',
    title: 'Quote',
    color: '#6366f1',
    deals: [
      {
        id: 'deal-1',
        client: 'Apex Industries',
        eventType: 'Corporate Retreat',
        value: 45000,
        probability: 60,
        daysInStage: 3,
        contactName: 'Michael Chen',
        services: ['Venue', 'Catering', 'AV Equipment'],
      },
      {
        id: 'deal-2',
        client: 'Summit Financial',
        eventType: 'Annual Gala',
        value: 85000,
        probability: 40,
        daysInStage: 5,
        contactName: 'Sarah Williams',
        services: ['Full Service', 'Entertainment'],
      },
    ],
  },
  {
    id: 'proposal',
    title: 'Proposal Sent',
    color: '#8b5cf6',
    deals: [
      {
        id: 'deal-3',
        client: 'TechVenture Labs',
        eventType: 'Product Launch',
        value: 120000,
        probability: 75,
        daysInStage: 2,
        contactName: 'James Rodriguez',
        services: ['Venue', 'Media Production', 'PR'],
      },
    ],
  },
  {
    id: 'contract',
    title: 'Contract Sent',
    color: '#a855f7',
    deals: [
      {
        id: 'deal-4',
        client: 'Morrison Family',
        eventType: 'Wedding Reception',
        value: 28000,
        probability: 90,
        daysInStage: 1,
        contactName: 'Emily Morrison',
        services: ['Venue', 'Catering', 'Decor'],
      },
      {
        id: 'deal-5',
        client: 'Global Health Initiative',
        eventType: 'Conference',
        value: 95000,
        probability: 85,
        daysInStage: 4,
        contactName: 'Dr. Amanda Foster',
        services: ['Venue', 'Catering', 'AV', 'Accommodation'],
      },
    ],
  },
  {
    id: 'booked',
    title: 'Booked',
    color: '#22c55e',
    deals: [
      {
        id: 'deal-6',
        client: 'Pinnacle Corp',
        eventType: 'Executive Summit',
        value: 150000,
        probability: 100,
        daysInStage: 0,
        contactName: 'Robert Chang',
        services: ['Full Service Package'],
        autoGenerated: true,
      },
    ],
  },
  {
    id: 'won',
    title: 'Delivered & Won',
    color: '#10b981',
    deals: [
      {
        id: 'deal-7',
        client: 'Sterling Foundation',
        eventType: 'Charity Gala',
        value: 75000,
        probability: 100,
        daysInStage: 0,
        contactName: 'Victoria Sterling',
        services: ['Full Service'],
      },
    ],
  },
];

export function SalesPipelineDemo() {
  const [columns, setColumns] = useState<ColumnData[]>(initialColumns);
  const [activeId, setActiveId] = useState<string | null>(null);
  const [automationLog, setAutomationLog] = useState<string[]>([
    '✓ Phase 1: Order validation complete',
    '✓ Phase 2: CRM opportunity linked',
    '✓ Phase 3: Task templates generated',
  ]);

  const sensors = useSensors(
    useSensor(PointerSensor, {
      activationConstraint: {
        distance: 8,
      },
    }),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  );

  // Calculate stats
  const totalValue = columns.reduce(
    (sum, col) => sum + col.deals.reduce((s, d) => s + d.value, 0),
    0
  );
  const totalDeals = columns.reduce((sum, col) => sum + col.deals.length, 0);
  const wonDeals = columns.find(c => c.id === 'won')?.deals.length || 0;
  const conversionRate = Math.round((wonDeals / totalDeals) * 100);
  const avgDealSize = Math.round(totalValue / totalDeals);

  const findContainer = (id: string) => {
    for (const column of columns) {
      if (column.deals.find((d) => d.id === id)) {
        return column.id;
      }
    }
    return null;
  };

  const getActiveCard = () => {
    if (!activeId) return null;
    for (const column of columns) {
      const deal = column.deals.find((d) => d.id === activeId);
      if (deal) return deal;
    }
    return null;
  };

  const handleDragStart = (event: DragStartEvent) => {
    setActiveId(event.active.id as string);
  };

  const handleDragEnd = (event: DragEndEvent) => {
    const { active, over } = event;
    setActiveId(null);

    if (!over) return;

    const activeContainer = findContainer(active.id as string);
    let overContainer = findContainer(over.id as string);
    
    // If over is a column, not a card
    if (!overContainer) {
      overContainer = columns.find(c => c.id === over.id)?.id || null;
    }

    if (!activeContainer || !overContainer) return;

    if (activeContainer !== overContainer) {
      // Move to different column
      setColumns((cols) => {
        const activeColIndex = cols.findIndex((c) => c.id === activeContainer);
        const overColIndex = cols.findIndex((c) => c.id === overContainer);

        const activeDealIndex = cols[activeColIndex].deals.findIndex(
          (d) => d.id === active.id
        );
        const deal = cols[activeColIndex].deals[activeDealIndex];

        // Log automation
        const fromStage = cols[activeColIndex].title;
        const toStage = cols[overColIndex].title;
        
        const newLog = [
          `→ Stage transition: ${fromStage} → ${toStage}`,
          `✓ 65+ fields synced across CRM, Sales, Projects`,
          `✓ Audit log entry created`,
        ];
        
        setAutomationLog((prev) => [...newLog, ...prev].slice(0, 8));

        const newCols = [...cols];
        newCols[activeColIndex] = {
          ...newCols[activeColIndex],
          deals: newCols[activeColIndex].deals.filter((d) => d.id !== active.id),
        };
        newCols[overColIndex] = {
          ...newCols[overColIndex],
          deals: [...newCols[overColIndex].deals, { ...deal, daysInStage: 0 }],
        };

        return newCols;
      });
    }
  };

  return (
    <DemoLayout
      title="Sales Pipeline Automation"
      subtitle="6-phase automation chain from Quote to Delivery"
    >
      {/* Stats Bar */}
      <div className={styles.statsBar}>
        <div className={styles.statItem}>
          <DollarSign className={styles.statIcon} />
          <div>
            <span className={styles.statLabel}>Pipeline Value</span>
            <span className={styles.statValue}>${(totalValue / 1000).toFixed(0)}K</span>
          </div>
        </div>
        <div className={styles.statItem}>
          <TrendingUp className={styles.statIcon} />
          <div>
            <span className={styles.statLabel}>Conversion</span>
            <span className={styles.statValue}>{conversionRate}%</span>
          </div>
        </div>
        <div className={styles.statItem}>
          <Users className={styles.statIcon} />
          <div>
            <span className={styles.statLabel}>Active Deals</span>
            <span className={styles.statValue}>{totalDeals}</span>
          </div>
        </div>
        <div className={styles.statItem}>
          <Clock className={styles.statIcon} />
          <div>
            <span className={styles.statLabel}>Avg Deal Size</span>
            <span className={styles.statValue}>${(avgDealSize / 1000).toFixed(0)}K</span>
          </div>
        </div>
      </div>

      <div className={styles.mainContent}>
        {/* Kanban Board */}
        <DndContext
          sensors={sensors}
          collisionDetection={closestCorners}
          onDragStart={handleDragStart}
          onDragEnd={handleDragEnd}
        >
          <div className={styles.kanbanBoard}>
            {columns.map((column) => (
              <KanbanColumn
                key={column.id}
                id={column.id}
                title={column.title}
                color={column.color}
                count={column.deals.length}
                totalValue={column.deals.reduce((s, d) => s + d.value, 0)}
              >
                <SortableContext
                  items={column.deals.map((d) => d.id)}
                  strategy={verticalListSortingStrategy}
                >
                  <AnimatePresence>
                    {column.deals.map((deal) => (
                      <KanbanCard key={deal.id} deal={deal} />
                    ))}
                  </AnimatePresence>
                </SortableContext>
              </KanbanColumn>
            ))}
          </div>

          <DragOverlay>
            {activeId ? <KanbanCard deal={getActiveCard()!} isDragging /> : null}
          </DragOverlay>
        </DndContext>

        {/* Automation Log */}
        <div className={styles.automationPanel}>
          <div className={styles.automationHeader}>
            <Zap className={styles.automationIcon} />
            <span>Automation Log</span>
          </div>
          <div className={styles.automationLog}>
            <AnimatePresence>
              {automationLog.map((log, i) => (
                <motion.div
                  key={`${log}-${i}`}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 20 }}
                  className={styles.logEntry}
                >
                  {log.startsWith('✓') ? (
                    <CheckCircle2 className={styles.logIconSuccess} />
                  ) : (
                    <span className={styles.logIconTransition}>→</span>
                  )}
                  <span>{log.replace(/^[✓→]\s*/, '')}</span>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
          <div className={styles.automationFooter}>
            <span className={styles.footerNote}>
              Zero manual re-entry between sales and operations
            </span>
          </div>
        </div>
      </div>
    </DemoLayout>
  );
}
